### PR TITLE
operator [CI] elastic-cloud-eck (2.12.0)

### PR DESCRIPTION
**Pull request by thbkrkr**
Update the ECK operator to the latest version `2.12.0`.

### CODE REVIEW

**Review by barkbay — APPROVED** [review]
LGTM

**Comment by thbkrkr** [comment]
Hello @dmesser, sorry for the direct ping. Maybe you could help to get this PR merged? We need to do patch release (`2.12.1`) as soon as possible. I imagine it is better to merge this PR first, before opening a new PR for the patch release.

**Comment by haripate** [comment]
@thbkrkr I will try to figure out the issue.

**Comment by haripate** [comment]
@thbkrkr I added a missing authorized-changes label, it should be merged automatically now.

**Comment by thbkrkr** [comment]
Thank you @haripate!

**Pull request merged**
