### PR TITLE
operators tektoncd-operator (0.24.1-1)

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [X] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [X] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [X] Have you tested your Operator with all Custom Resource Definitions?
* [X] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [X] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [X] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [X] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [X] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [X] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [X] Have you tested an update to your Operator when deployed via OLM?
* [X] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [X] Human readable name and 1-liner description about your Operator
* [X] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [X] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [X] Links to the maintainer, source code and documentation
* [X] Example templates for all Custom Resource Definitions intended to be used
* [X] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by J0zi** [comment]
@nikhil-thomas CRD delete test failed, please have a look https://github.com/k8s-operatorhub/community-operators/pull/67/checks?check_run_id=3201807430#step:3:999.

**Comment by nikhil-thomas** [comment]
@J0zi yup, im trying to run the tests on my local machine using the test-suite script and figure out what is happening.
https://k8s-operatorhub.github.io/community-operators/operator-test-suite/ 🤔

**Comment by nikhil-thomas** [comment]
```
  cmd: kubectl delete -f /tmp/operator-test/operator-files/manifests/operator.tekton.dev_tektonpipelines.yaml --ignore-not-found=true --timeout=60s
...
  stderr: 'error: timed out waiting for the condition on customresourcedefinitions/tektonpipelines.operator.tekton.dev'
```
@J0zi what is happening is that, this operator creates an instance of its CRDs automatically.

It looks like kiwi test is removing the operator controller before it removes the CRD. So there is nobody to remove the finalizer that the controller is setting on the instance of the ownedCRDs.

We have this `autocreation` feature behind a config flag. we can set it to false (no autocreation) and the kiwi tests pass.
In the previous, releases we didn't have this feature.

Is there any other way to keep the `autocreation` enabled and get this pr merged.

**Comment by nikhil-thomas** [comment]
@J0zi we shall merge this without the `autoinstall` feature in this patch.
is there a hook/config on this ci that we can read from the operator controller and make some changes in our logic. I promise that we will use it responsibily 🧑‍💻 👍

**Pull request merged**
