### PR TITLE
operator opentelemetry-operator (0.74.0)

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Release opentelemetry-operator `0.74.0`.

cc @pavolloffay @frzifus @yuriolisa @jaronoff97 @VineethReddy02

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Review by frzifus — APPROVED** [review]

**Comment by mporrato** [comment]
> Sorry to hijack the PR, but why am I being pinged? I thought it would be sufficient to not have me as part of ci.yaml, but I'm already not part of it for this operator...

You are listed as a reviewer in ci.yaml for this operator.

**Comment by pavolloffay** [comment]
@jpkrohling I have removed you form the ci.yaml today.

**Comment by jpkrohling** [comment]
Thanks @pavolloffay, that was my confusion then :-)

**Comment by pavolloffay** [comment]
The bot cannot fix this PR. Here is a new one https://github.com/k8s-operatorhub/community-operators/pull/2566

**Pull request closed without merging**
