### PR TITLE
operator [N] [CI] oracle-database-operator (v1.1.0)

### PR DESCRIPTION
**Pull request by psilberk**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)? Yes
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework? Yes
* [ ] Have you tested your Operator with all Custom Resource Definitions? Yes
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)? Yes
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)? Yes
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)? Yes
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set? Yes

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by psilberk** [comment]
@haripate @tomasbakk I've been trying to create this pull request for our Operator (Oracle) but it's becoming impossible to walk-around some checks. Can I get some support from you? Tahnsk

**Comment by haripate** [comment]
> @haripate @tomasbakk I've been trying to create this pull request for our Operator (Oracle) but it's becoming impossible to walk-around some checks. Can I get some support from you? Tahnsk

I will take a look into it.

**Comment by haripate** [comment]
There are couple of issues I found:

1. The value of [containerImage](https://github.com/k8s-operatorhub/community-operators/blob/423ec1dba7055920e22fc89d3f45a2238ff85250/operators/oracle-database-operator/v1.1.0/manifests/oracle-database-operator.clusterserviceversion.yaml#L457) and [image](https://github.com/k8s-operatorhub/community-operators/blob/423ec1dba7055920e22fc89d3f45a2238ff85250/operators/oracle-database-operator/v1.1.0/manifests/oracle-database-operator.clusterserviceversion.yaml#L589) field should be same. This means you need to use the same image in the container as you mentioned in containerImage field.
2. The `ci.yaml` file is missing in the submitted changes. Please review [this document](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md#submitting-your-operator-via-pull-requests-pr-in-community-operators-project) for reference.

Let me know if you still face any issues.

**Comment by psilberk** [comment]
Thanks, I'll review this.
With respect to the commits signoff, I've been trying the latest commits with --signoff and still have the error. Any recommendation to solve this?

**Comment by haripate** [comment]
> Thanks @haripate , I'll review this. With respect to the commits signoff, I've been trying the latest commits with --signoff and still have the error. Any recommendation to solve this?

Looks like few previous commits are missing sign-offs.
Please follow the below steps.

1. In your local branch, run: git rebase HEAD~7 --signoff
2. Force push your changes to overwrite the branch: git push --force-with-lease origin <your_branch>

**Comment by psilberk** [comment]
Thanks @haripate , but it looks like the signoff didn't work and there's another error (maybe because the signoff didn't work?): fatal: [localhost]: FAILED! => changed=false 
  msg: Operator was not found among packagemanifests

**Comment by psilberk** [comment]
Hi @haripate @tomasbakk I fixed the previous errors and rebased the commits. 
I still some error but I can't find in the 'details' what was wrong (other than some warnings).
Could you please advice?
Thanks

**Comment by psilberk** [comment]
> Hi @haripate @tomasbakk I fixed the previous errors and rebased the commits. I still got an error in the mail but I can't find in the 'details' what was wrong (other than some warnings). Could you please advice? Thanks

Hi guys, sorry for keep reaching out, but at this point I don't know how to fix the validation, so if you can't provide any insights I will just drop Oracle's contribution to this project.

**Comment by haripate** [comment]
@psilberk I will look into the issue.

**Comment by haripate** [comment]
@mporrato could you help Pablo to figure out this issue?

**Comment by mporrato** [comment]
@psilberk Looks like something went wrong in the rebase: I see there are over 300 modified files across multiple operators. I would suggest closing this PR and submit a new one from scratch.

**Comment by psilberk** [comment]
Trying another one from scratch

**Pull request closed without merging**
