### PR TITLE
operators kubernetes-imagepuller-operator (0.1.0)

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by ibuziuk** [comment]
@J0zi @mvalarh folks, could you please re-trigger the tests. 
Not sure what is wrong with the kiwi test, but a similar PR to `community-operators-prod` is green -  https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/460

**Comment by NissesSenap** [comment]
@ibuziuk if you just signoff of your commit and amend and force push it the PR will trigger again.

**Comment by tolusha** [comment]
@NissesSenap 
Hi. Could you help me how to find the cause of failed test? 
Is there any meaningful logs?

I can see

```
TASK [operator_ignore_list : Build index image 'kind-registry:5000/test-operator/catalog:latesti'] ***
fatal: [localhost]: FAILED! => changed=true 
  cmd: podman pull kind-registry:5000/test-operator/catalog:latesti
  delta: '0:00:00.137303'
  end: '2021-11-19 08:35:29.935298'
  msg: non-zero return code
  rc: 125
  start: '2021-11-19 08:35:29.797995'
  stderr: |-
    Trying to pull kind-registry:5000/test-operator/catalog:latesti...
    Error: initializing source docker://kind-registry:5000/test-operator/catalog:latesti: reading manifest latesti in kind-registry:5000/test-operator/catalog: manifest unknown: manifest unknown
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
```

Is that a culprit?

**Comment by NissesSenap** [comment]
No idea @tolusha I just saw your PR and ibuziuk asking for help to retrigger the PR and wrote how to do it since I retriggered the PR myself.

**Comment by AndrienkoAleksandr** [comment]
I see the reason of the failing in the github action logs(strange but error text is green):

> api-server resource not found installing ServiceMonitor controller-manager-metrics-monitor: GroupVersionKind monitoring.coreos.com/v1, Kind=ServiceMonitor not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.

But I'm wondering if OLM doesn't handle this case, because when we generate bundle with  enabled metrics feature, ServiceMonitor yaml included to the bundle. But then we can see failing this operator during installation on some clusters without no CRDs for this ServiceMonitor k8s resource...

**Pull request merged**
