### PR TITLE
operator [O] splunk (2.0.0)

### PR DESCRIPTION
**Pull request by vivekr-splunk**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by vivekr-splunk** [comment]
> Dear @vivekr-splunk, Some errors and/or warnings were found while doing the check of your operator (`splunk/2.0.0`) against the entire suite of validators for Operator Framework with [Operator-SDK](https://github.com/operator-framework/operator-sdk) version `v1.19.1` and the command `$ operator-sdk bundle validate <bundle-path> --select-optional suite=operatorframework`.
> 
> **Errors (🐛) must be fixed while warnings (⚠️) are informative, and fixing them might improve the quality of your solution.**
> 
> Type	Message
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value : found olm.properties annotation, please define these properties in metadata/properties.yaml instead



> Dear @vivekr-splunk, Some errors and/or warnings were found while doing the check of your operator (`splunk/2.0.0`) against the entire suite of validators for Operator Framework with [Operator-SDK](https://github.com/operator-framework/operator-sdk) version `v1.19.1` and the command `$ operator-sdk bundle validate <bundle-path> --select-optional suite=operatorframework`.
> 
> **Errors (🐛) must be fixed while warnings (⚠️) are informative, and fixing them might improve the quality of your solution.**
> 
> Type	Message
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta3, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta2, Kind=SearchHeadCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1alpha1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1, Kind=ClusterMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v2, Kind=LicenseMaster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=IndexerCluster: provided API should have an example annotation
> ⚠️	Value enterprise.splunk.com/v1beta1, Kind=Standalone: provided API should have an example annotation
> ⚠️	Value : found olm.properties annotation, please define these properties in metadata/properties.yaml instead

can we add 'allow/longer-deployment' label, its creating emptydir as volume. i am not sure if that is taking time or its failing due to the above volume. let me know what log files I can check. locally it works.

**Comment by J0zi** [comment]
@vivekr-splunk I noticed following. What do you think?

```
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-08-05T16:18:18Z"
      message: '0/1 nodes are available: 1 Insufficient cpu.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
```

**Comment by vivekr-splunk** [comment]
> 

I have changes the resource limit , will it work now
`                resources:
                  limits:
                    cpu: 500m
                    memory: 2000Mi
                  requests:
                    cpu: 100m
                    memory: 500Mi
`

**Pull request closed without merging**
