### PR TITLE
operator splunk (2.1.0)

### PR DESCRIPTION
**Pull request by vivekr-splunk**
Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by vivekr-splunk** [comment]
Is there anyway to find what is the issue , how can I check the log file why the operator was unable to get deployed. any help is appreciated.

**Comment by vivekr-splunk** [comment]
I am unable to find why the pod is not getting deployed. can someone help me to find the issue. Is there anyway to check the events of the pod. on my local system deployment works fine.

**Comment by J0zi** [comment]
@vivekr-splunk did you tested your operator on k8s `v1.24.0` locally? Pipeline is unable to start the operator.

**Comment by vivekr-splunk** [comment]
@J0zi thanks for looking at this issue. i am trying to run locally but it fails with following error. the same bundle is certified by redhat already
```   time="2022-12-22T21:09:42Z" level=warning msg="Failed, retrying in 1s ... (3/3). Error: trying to reuse blob sha256:065152115aa916aefc9c302fa837305d8d8acb9c8de0246b4b710cb775ad6085 at destination: pinging container registry kind-registry:5000: Get \"https://kind-registry:5000/v2/\": dial tcp 127.0.0.1:5000: connect: connection refused"
    time="2022-12-22T21:09:43Z" level=warning msg="error reading certificate \"/etc/containers/certs.d/kind-registry:5000/ca.crt\": open /etc/containers/certs.d/kind-registry:5000/ca.crt: no such file or directory"
    Getting image source signatures
    Copying blob sha256:5ccae692f68941ab4fc9ed7bd004af249183bde86dbe5a85a615d1c325ac954b
    Copying blob sha256:5cec1e2edb39dc0f32de0e5c435d232da138403873c47b7c85bd8e1d88c8b489
    Copying blob sha256:065152115aa916aefc9c302fa837305d8d8acb9c8de0246b4b710cb775ad6085
    Error: trying to reuse blob sha256:065152115aa916aefc9c302fa837305d8d8acb9c8de0246b4b710cb775ad6085 at destination: pinging container registry kind-registry:5000: Get "https://kind-registry:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring```

**Comment by vivekr-splunk** [comment]
I am not sure how to set the kind registry here. command I running locally is
```OPP_PRODUCTION_TYPE=k8s \
OPP_DEBUG=1 \
OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL=1  \
OPP_RELEASE_INDEX_NAME="catalog_tmp" \
bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
kiwi \
operators/splunk/2.1.1 \
vivekr-splunk/community-operators.git  \
main```

**Pull request closed without merging**
