### PR TITLE
operator tempo-operator (0.14.1)

### PR DESCRIPTION
**Pull request by tempooperatorbot**
Release tempo-operator `0.14.1`.

cc @pavolloffay @frzifus @andreasgerstmayr @rubenvp8510 @iblancasa

### CODE REVIEW

**Review by frzifus — APPROVED** [review]

**Review by iblancasa — APPROVED** [review]

**Comment by mantomas** [comment]
You need to do a `/hold` followed by a `/hold cancel` to approve the merge. Described in [docs here.](https://k8s-operatorhub.github.io/community-operators/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator)

**Review by andreasgerstmayr — APPROVED** [review]

**Comment by andreasgerstmayr** [comment]
> You need to do a `/hold` followed by a `/hold cancel` to approve the merge. Described in [docs here.](https://k8s-operatorhub.github.io/community-operators/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator)

Nice, thanks for the tip!

**Pull request merged**
