### PR TITLE
operators argocd-operator (0.3.0)

### PR DESCRIPTION
**Pull request by ishitasequeira**
Signed-off-by: ishitasequeira [ishiseq29@gmail.com](mailto:ishiseq29@@gmail.com)

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Review by iam-veeramalla — APPROVED** [review]

**Comment by iam-veeramalla** [comment]
@J0zi @mvalarh 
I approved the PR and was expecting the CI bot to set `authorized_changes` label.

I came across this. Does this mean either of you have to approve this PR ?
```
Pipeline will set authorized_changes label only if last github reviewer is in reviewer list (defined in ci.yaml) and review state is APPROVED
```
https://redhat-openshift-ecosystem.github.io/community-operators-prod/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator

**Comment by mvalarh** [comment]
> @J0zi @mvalarh I approved the PR and was expecting the CI bot to set `authorized_changes` label.
> 
> I came across the below statement in the docs. Does this mean either of you have to approve this PR ?
> 
> ```
> Pipeline will set authorized_changes label only if last github reviewer is in reviewer list (defined in ci.yaml) and review state is APPROVED
> ```
> 
> https://redhat-openshift-ecosystem.github.io/community-operators-prod/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator

There are several options one can get `authorized_changes` label if author is not in reviewer list. Please see `Author is not in reviewer list`. In your case you could `approve` and then `/hold` and '\unhold'.

**Comment by iam-veeramalla** [comment]
> > @J0zi @mvalarh I approved the PR and was expecting the CI bot to set `authorized_changes` label.
> > I came across the below statement in the docs. Does this mean either of you have to approve this PR ?
> > ```
> > Pipeline will set authorized_changes label only if last github reviewer is in reviewer list (defined in ci.yaml) and review state is APPROVED
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://redhat-openshift-ecosystem.github.io/community-operators-prod/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator
> 
> There are several options one can get `authorized_changes` label if author is not in reviewer list. Please see `Author is not in reviewer list`. In your case you could `approve` and then `/hold` and `/unhold`.

@mvalarh ah I over looked into the docs. I thought I just need to approve, missed the `/hold` and `unhold` part. Thanks :)

**Pull request merged**
