### PR TITLE
operator cc-operator (0.2.0)

### PR DESCRIPTION
**Pull request by jensfr**
Signed-off-by: Jens Freimann <jfreimann@redhat.com>

Just updating the description.

### CODE REVIEW

**Comment by mvalarh** [comment]
@jensfr please rebase to latest main. THanks

**Comment by J0zi** [comment]
@jensfr please rebase.

**Comment by J0zi** [comment]
@jensfr any update?

**Comment by J0zi** [comment]
@jensfr feel free to reopen any time. Rebase is needed.

**Pull request closed without merging**
