### PR TITLE
operator [N] [CI] node-maintenance-operator (0.13.1)

### PR DESCRIPTION
**Pull request by razo7**
Signed-off-by: oraz <oraz@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by J0zi** [comment]
@razo7 please check why it is `Unschedulable`
```
    - lastProbeTime: null
      lastTransitionTime: "2022-08-24T12:45:46Z"
      message: '0/1 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector.
        preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
```
https://github.com/k8s-operatorhub/community-operators/runs/7994979359?check_suite_focus=true

**Comment by J0zi** [comment]
maybe an empty value is causing the issue, not sure. There is this selector with empty value  used many times https://github.com/k8s-operatorhub/community-operators/pull/1624/files#diff-ac49f578dda798573643c376ad34abc5a678781e4bb6ef5d30401cb307769ca5R213

**Comment by razo7** [comment]
According to the [KEP-2067 ](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint#summary) a new taint and label ("control-plane"), node-role.kubernetes.io/control-plane, should replace the old taint and label ("master"), node-role.kubernetes.io/master.

I suspect that this is the cause of the K8s CI test (kiwi) to fail, since the operator's [pod should be placed on a _master_ node](https://github.com/medik8s/node-maintenance-operator/blob/main/bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml#L226-L232), and there is no master node in the cluster (if the cluster uses the new K8s version, [`master`-> `control-plane`](https://github.com/medik8s/node-maintenance-operator/pull/52)).  
Which version of Kubernetes the Kiwi test uses? @J0zi @mvalarh 

Similarly NHC has the same problem of [node affinity](https://github.com/medik8s/node-healthcheck-operator/blob/main/bundle/manifests/node-healthcheck-operator.clusterserviceversion.yaml#L306-L307) in https://github.com/k8s-operatorhub/community-operators/pull/1652.

**Comment by J0zi** [comment]
@razo7 in this case we are running `v1.24.0`. Consider making it universally working. Because people may have problems to install it also.

**Comment by razo7** [comment]
@J0zi @mvalarh can you approve this PR?

**Pull request merged**
