### PR TITLE
operators [R] jaeger (1.33.0 1.34.0 1.34.1 1.35.0)

### PR DESCRIPTION
**Pull request by frzifus**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Submit operators to both `upstream-community-operators` and `community-operators` at once
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by frzifus** [comment]
mh...
```bash
    - time="2022-06-21T22:10:26Z" level=info msg="jaeger-operator.v1.34.1 replaced by jaeger-operator.v1.35.0"
    - time="2022-06-21T22:10:26Z" level=info msg="Processing olmConfig"
    - 'I0621 22:10:26.971164       1 event.go:282] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"default", Name:"jaeger-operator.v1.35.0", UID:"1ac3d983-4ff6-4de3-b517-5d7fc6dda24a", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"2511", FieldPath:""}): type: ''Warning'' reason: ''InstallComponentFailed'' install strategy failed: Deployment.apps "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable'
    - time="2022-06-21T22:10:27Z" level=info msg="checking jaeger-operator.v1.34.1"
    - time="2022-06-21T22:10:27Z" level=info msg="checking jaeger-operator.v1.35.0"
    - time="2022-06-21T22:10:27Z" level=info msg="jaeger-operator.v1.34.1 replaced by jaeger-operator.v1.35.0"
```

**Comment by J0zi** [comment]
@frzifus are you able to upgrade from `v1.34.1` bundle to `v1.35.0` bundle locally? You can use `operator-sdk` and debug the issue.

**Comment by frzifus** [comment]
Hi @J0zi, i will try it in a minute. But i expect it will not work. In 1.33.0 we introduced a new label `app.kubernetes.io/name: jaeger-operator`. Afterwards we notcied [upgrading from 1.32 to 1.33 didnt work](https://github.com/jaegertracing/jaeger-operator/issues/1870). To avoid issues while upgrading the productized version from 1.30 to [1.34 + patch](https://github.com/jaegertracing/jaeger-operator/pull/1920) we removed the label. ([changelog](https://github.com/jaegertracing/jaeger-operator/blob/main/CHANGELOG.md#1350-2022-06-16))
```bash
The Deployment "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"[app.kubernetes.io/name](http://app.kubernetes.io/name)":"jaeger-operator", "name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
Now here seems to be the other way around? :face_exhaling: I wonder that we didnt notice it during the 1.33.0 release.
```bash
    - 'I0621 22:10:26.971164       1 event.go:282] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"default", Name:"jaeger-operator.v1.35.0", UID:"1ac3d983-4ff6-4de3-b517-5d7fc6dda24a", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"2511", FieldPath:""}): type: ''Warning'' reason: ''InstallComponentFailed'' install strategy failed: Deployment.apps "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable'
```

**Comment by frzifus** [comment]
Ive no clue how to solve this issue other then removing the label in older releases too. It would also solve our upgrade issue from 1.32 to 1.33. But what i also dont know, how will it affect people they already use 1.33 or 1.34.x? 

In case we go that path, should we create an extra PR or just squash it in? 

see: https://github.com/k8s-operatorhub/community-operators/pull/1366/commits/a5466d1bbb864cceaa09964f4117fab817a80115

What do you think @J0zi ?

**Comment by frzifus** [comment]
mh.. another way could be to replace 1.32 instead of higher versions. That would just requiere a reinstall for 1.33 and 1.34.x.

**Comment by J0zi** [comment]
@frzifus please test how it affects people who already use it and fix accordingly.

**Comment by frzifus** [comment]
just for the record: previously it was not possible to upgrade from 1.32 to 1.33. Without changing the older bundles too, this would occur during an upgrade from 1.34 to 1.35 again.

Those kind of issues can be resolved using:
```
kubectl delete deployments.apps -n operators jaeger-operator
```

Now its only necessary in case 1.33 or 1.34 is already installed. In case its not detected, the worst consequence is that you will stuck on your operator version and not get an upgrade.

Logs:
```bash
time="2022-07-12T08:41:42Z" level=info msg="checking cert-manager.v1.8.0"
time="2022-07-12T08:41:42Z" level=info msg="checking jaeger-operator.v1.32.0"
time="2022-07-12T08:41:42Z" level=info msg="checking jaeger-operator.v1.33.0"
time="2022-07-12T08:41:42Z" level=info msg="jaeger-operator.v1.32.0 replaced by jaeger-operator.v1.33.0"
time="2022-07-12T08:41:42Z" level=info msg="Processing olmConfig"
time="2022-07-12T08:41:42Z" level=info msg="Processing olmConfig"
time="2022-07-12T08:41:42Z" level=info msg="Processing olmConfig"
time="2022-07-12T08:41:42Z" level=warning msg="reusing existing cert jaeger-operator-service-cert"
I0712 08:41:43.061567       1 event.go:282] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"jaeger-operator.v1.33.0", UID:"a19abef9-4ba8-4f8e-9037-145cab18b5ad", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"5238", FieldPath:""}): type: 'Warning' reason: 'InstallComponentFailed' install strategy failed: Deployment.apps "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"jaeger-operator", "name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
{"level":"error","ts":1657615303.1696794,"logger":"controllers.operator","msg":"Could not update Operator status","request":"/jaeger.operators","error":"Operation cannot be fulfilled on operators.operators.coreos.com \"jaeger.operators\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1657615303.267872,"logger":"controllers.operator","msg":"Could not update Operator status","request":"/jaeger.operators","error":"Operation cannot be fulfilled on operators.operators.coreos.com \"jaeger.operators\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
E0712 08:41:43.366777       1 queueinformer_operator.go:290] sync {"update" "operators/jaeger-operator.v1.33.0"} failed: Deployment.apps "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"jaeger-operator", "name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Pull request merged**
