### PR TITLE
operators [N] [CI] special-resource-operator (4.8.1)

### PR DESCRIPTION
**Pull request by pacevedom**
Signed-off-by: Pablo Acevedo Montserrat <pacevedo@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by pacevedom** [comment]
@J0zi @mvalarh the deploy test is failing because this operator requires another one to be deployed alongside, is this supported in this repo? The CSV already states a dependency.

**Comment by J0zi** [comment]
@pacevedom pipeline reporting dependency, but it is reporting SRO operator. So no dependency, it failed to run SRO operator. Were you able to run the operator by yourself somewhere?

**Comment by pacevedom** [comment]
@J0zi just packaing everything in containers, creating an index, a catalog source, and then deploying the operator through OLM worked on the first try. 
```
❯ oc get catalogsources.operators.coreos.com -n openshift-marketplace special-resource-operator-catalog -o yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"CatalogSource","metadata":{"annotations":{},"name":"special-resource-operator-catalog","namespace":"openshift-marketplace"},"spec":{"displayName":"test catalog","image":"quay.io/pacevedo/srobundle:catalog","publisher":"test-catalog","sourceType":"grpc"}}
  creationTimestamp: "2021-09-21T12:28:20Z"
  generation: 1
  name: special-resource-operator-catalog
  namespace: openshift-marketplace
  resourceVersion: "32472"
  uid: c5ae8486-f1df-4d86-85b8-3278acb67f53
spec:
  displayName: test catalog
  image: quay.io/pacevedo/srobundle:catalog
  publisher: test-catalog
  sourceType: grpc
status:
  connectionState:
    address: special-resource-operator-catalog.openshift-marketplace.svc:50051
    lastConnect: "2021-09-21T12:30:27Z"
    lastObservedState: READY
  registryService:
    createdAt: "2021-09-21T12:28:20Z"
    port: "50051"
    protocol: grpc
    serviceName: special-resource-operator-catalog
    serviceNamespace: openshift-marketplace

❯ oc get subscriptions -n openshift-special-resource-operator
NAME                                             PACKAGE                     SOURCE                              CHANNEL
nfd-4.8-redhat-operators-openshift-marketplace   nfd                         redhat-operators                    4.8
special-resource-operator                        special-resource-operator   special-resource-operator-catalog   alpha

❯ oc get pod -n openshift-special-resource-operator
NAME                                                   READY   STATUS    RESTARTS   AGE
nfd-controller-manager-8b747d87-tjchk                  2/2     Running   0          6m11s
special-resource-controller-manager-676cb965cc-6f6lx   2/2     Running   0          6m7s
```

**Comment by J0zi** [comment]
@pacevedom I don't see the reason where is it failing. It could help you run it locally with same setup as pipeline has by executing 
```
cd <community-operators>
bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
<test-type1,test-type2,...,test-typeN> \
<operator-version-dir-relative-to-community-operators-project> \
[<git repo>] [<git branch>]
```
more info [here](https://github.com/redhat-openshift-ecosystem/community-operators-pipeline/blob/documentation/docs/operator-test-suite.md)

Then you can debug directly.

**Pull request closed without merging**
