### PR TITLE
operators elastic-cloud-eck (2.2.0)

### PR DESCRIPTION
**Pull request by naemono**
Updates ECK Elasticsearch operator to the latest version 2.2.0

### CODE REVIEW

**Comment by J0zi** [comment]
@naemono please check channels.

**Comment by naemono** [comment]
@J0zi The only change to channels is https://github.com/k8s-operatorhub/community-operators/pull/1181/files#diff-535e8ce84461ae24edda7b79f702f631a3dacccfa1d1ea7f551be7f79a668d60, and the naming of the CSV is staying consistent across versions.

Am I missing something?  Thanks for any pointers you can provide.

**Comment by mvalarh** [comment]
@naemono i found it. Somehow `package.yaml` file is not changed while we are rebasing your branch to our main. Will you be so kind to rebase to current main? Thank you very much

**Comment by naemono** [comment]
@mvalarh git did an auto-merge, instead of a rebase.  Hope that's ok.  Thanks for your help with this.

**Comment by mvalarh** [comment]
It seams to me that it didn't help. Very strange. Our pipeline is doing
```
git clone https://github.com/naemono/community-operators
cd community-operators
git checkout origin/2.2.0
```
And at this stage we have `elastic-cloud-eck.v2.2.0` which is correct
```
$ cat operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml 
channels:
- currentCSV: elastic-cloud-eck.v2.2.0
  name: stable
defaultChannel: stable
```
Then we do
```
git remote add upstream https://github.com/k8s-operatorhub/community-operators
git pull --rebase -Xours upstream main
```
and package file is old one. Very strange for me
```
$ cat operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml 
channels:
- currentCSV: elastic-cloud-eck.v2.1.0
  name: stable
defaultChannel: stable
packageName: elastic-cloud-eck
```

Can you test it locally please? If it will not work. Can you make new PR?

**Pull request merged**
