### PR TITLE
operators grafana-operator (3.10.4)

### PR DESCRIPTION
**Pull request by pb82**
Signed-off-by: Peter Braun <pbraun@redhat.com>

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

### CODE REVIEW

**Comment by HubertStefanski** [comment]
hey @mvalarh , seems like `Kiwi` is failing on unrelated issues? Is this a problem with the test itself? I noticed that the bundle image is tagged `latesti` instead of `latest`, would that be the issue? that's stopping the test from progressing past the image pull?

**Comment by mvalarh** [comment]
@pb82 and @HubertStefanski . I think your problem is

```
      Type     Reason               Age                    From                        Message
      ----     ------               ----                   ----                        -------
      Normal   RequirementsUnknown  14m                    operator-lifecycle-manager  requirements not yet checked
      Normal   RequirementsNotMet   14m                    operator-lifecycle-manager  one or more requirements couldn't be found
      Normal   InstallWaiting       9m35s (x2 over 14m)    operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: deployment "grafana-operator" not available: Deployment does not have minimum availability.
      Normal   AllRequirementsMet   4m35s (x4 over 14m)    operator-lifecycle-manager  all requirements found, attempting install
      Normal   InstallSucceeded     4m35s (x6 over 14m)    operator-lifecycle-manager  waiting for install components to report healthy
      Warning  InstallCheckFailed   4m35s (x4 over 9m35s)  operator-lifecycle-manager  install timeout
      Normal   NeedsReinstall       4m35s (x3 over 9m35s)  operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: deployment "grafana-operator" not available: Deployment does not have minimum availability.
      Normal   InstallWaiting       4m34s                  operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: waiting for spec update of deployment "grafana-operator" to be observed...
      Warning  InstallCheckFailed   4m34s (x3 over 4m34s)  operator-lifecycle-manager  install failed: deployment grafana-operator not ready before timeout: deployment "grafana-operator" exceeded its progress deadline
      Type     Reason               Age                    From                        Message
      ----     ------               ----                   ----                        -------
      Normal   RequirementsUnknown  14m                    operator-lifecycle-manager  requirements not yet checked
      Normal   RequirementsNotMet   14m                    operator-lifecycle-manager  one or more requirements couldn't be found
      Normal   InstallWaiting       9m35s (x2 over 14m)    operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: deployment "grafana-operator" not available: Deployment does not have minimum availability.
      Normal   AllRequirementsMet   4m35s (x4 over 14m)    operator-lifecycle-manager  all requirements found, attempting install
      Normal   InstallSucceeded     4m35s (x6 over 14m)    operator-lifecycle-manager  waiting for install components to report healthy
      Warning  InstallCheckFailed   4m35s (x4 over 9m35s)  operator-lifecycle-manager  install timeout
      Normal   NeedsReinstall       4m35s (x3 over 9m35s)  operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: deployment "grafana-operator" not available: Deployment does not have minimum availability.
      Normal   InstallWaiting       4m34s                  operator-lifecycle-manager  installing: waiting for deployment grafana-operator to become ready: waiting for spec update of deployment "grafana-operator" to be observed...
      Warning  InstallCheckFailed   4m34s (x3 over 4m34s)  operator-lifecycle-manager  install failed: deployment grafana-operator not ready before timeout: deployment "grafana-operator" exceeded its progress deadline
```
Problem not finding `latesti` is ok in case of testing. I fixed this not to show error, since it is not

**Comment by J0zi** [comment]
@pb82 how is your local investigation going?

**Comment by J0zi** [comment]
Feel free to reopen when needed

**Pull request closed without merging**
