### PR TITLE
operator mongodb-enterprise (1.19.1)

### PR DESCRIPTION
**Pull request by mms-build-account**
This PR has been created by MongoDB Release Automation Tool.

If additional details are needed, please contact any authorized
reviewer from MongoDB.

### CODE REVIEW

**Comment by dmesser** [comment]
See comment here about the failing test: https://github.com/k8s-operatorhub/community-operators/issues/2610#issuecomment-1520673134

**Comment by dmesser** [comment]
@mporrato could you take a look at this one? For some reason it is not finding the registry pod. But I think the original problem is that the CSV doesn't become healthy. @mircea-cosbuc have you tested this update locally?

**Comment by mircea-cosbuc** [comment]
@dmesser @mporrato We did test this update locally (running the whole orange pipeline with the ansible playbooks) , but it only succeeded after setting the environment variable:
```
export KIND_KUBE_VERSION=v1.24.0
```
We noticed that by default the orange pipeline will use a version of `1.21.1` which would indeed lead the CSV in a non-healthy state since the `minKubeVersion` is set to `1.23.0`. It is not clear if the `1.12.1` version of kube for the test is set because of the bundle or the CI configuration.

**Comment by mporrato** [comment]
@mircea-cosbuc I just deployed a fix for the CI that should pick up the right k8s version for lemon and orange tests.
I'll close and reopen this PR to let the CI use the fixed GH action.

**Comment by mircea-cosbuc** [comment]
@mporrato Thank you for following up on this and helping with getting it merged! 🎉

**Pull request merged**
