### PR TITLE
operator [N] [CI] nri-plugins-operator (0.3.2)

### PR DESCRIPTION
**Pull request by fmuyassarov**
Submit nri-plugins-operator (0.3.2) initial version.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Hi @Allda @mporrato 
In our operator GitHub repo we are using custom [categories.json](https://github.com/containers/nri-plugins/blob/main/deployment/operator/categories.json). But when we bundled the operator for submission PR checks failed because it doesn’t recognize our custom category.

We can fix the category in the operator but then we need to cut a release again and then bundle it - just for the category change right? Or is there a way to avoid cutting a new release in our operator to pass this failed check here?

**Comment by fmuyassarov** [comment]
> Hi @Allda @mporrato In our operator GitHub repo we are using custom [categories.json](https://github.com/containers/nri-plugins/blob/main/deployment/operator/categories.json). But when we bundled the operator for submission PR checks failed because it doesn’t recognize our custom category.
> 
> We can fix the category in the operator but then we need to cut a release again and then bundle it - just for the category change right? Or is there a way to avoid cutting a new release in our operator to pass this failed check here?

We did cut a new release v0.3.1 and bundle is now updated accordingly.

**Review by kad — APPROVED** [review]
Looks good.

**Comment by fmuyassarov** [comment]
approve

**Comment by fmuyassarov** [comment]
Hi @Allda,
Would you mind to give authorized label or approve the PR? I think it is not getting merged since it is a new operator but probably for the following releases we will be able to merge it ourselves.

**Comment by Allda** [comment]
@fmuyassarov Hey, yes that's correct. New operator needs to be reviewd by some of us. Followup will be merged automatically based on you ci.yaml config. Thanks for your contribution!

**Pull request merged**
