### PR TITLE
operator [CI] stackgres (1.5.0)

### PR DESCRIPTION
**Pull request by teoincontatto**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by teoincontatto** [comment]
The failed check only report an error with `kubectl logs` command can someone shed some light on why it is failing?

```
 fatal: [localhost]: FAILED! => changed=true 
  cmd: kubectl logs  -n default
  delta: '0:00:00.048794'
  end: '2023-07-05 08:12:39.926491'
  msg: non-zero return code
  rc: 1
  start: '2023-07-05 08:12:39.877697'
  stderr: |-
    error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
    POD or TYPE/NAME is a required argument for the logs command
    See 'kubectl logs -h' for help and examples
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
```

**Comment by teoincontatto** [comment]
Trying to reproduce the issue locally was not possible since the instruction given do not allow to test the upgrade and end up with a failure when installing stackgres 1.5.0 on top of 1.4.3 (using operator-sdk v1.28.0):

> ```
> TASK [test_operator_update : Update status if wrong] ***************************
> fatal: [localhost]: FAILED! => changed=false 
>   msg: 'Operator upgrade failed, you can debug locally by 2 commands: ''operator sdk run bundle BUNDLE_N-1; operator-sdk run bundle-upgrade BUNDLE_N''  [FAIL]'
> ```

```
$ operator-sdk run bundle registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.4.3
INFO[0013] Creating a File-Based Catalog of the bundle "registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.4.3" 
INFO[0016] Generated a valid File-Based Catalog         
INFO[0019] Created registry pod: istry-gitlab-com-ongresinc-stackgres-helm-operator-bundle-1-4-3 
INFO[0019] Created CatalogSource: stackgres-catalog     
INFO[0019] OperatorGroup "operator-sdk-og" created      
INFO[0019] Created Subscription: stackgres-v1-4-3-sub   
INFO[0031] Approved InstallPlan install-zknjf for the Subscription: stackgres-v1-4-3-sub 
INFO[0031] Waiting for ClusterServiceVersion "default/stackgres.v1.4.3" to reach 'Succeeded' phase 
INFO[0031]   Waiting for ClusterServiceVersion "default/stackgres.v1.4.3" to appear 
INFO[0034]   Found ClusterServiceVersion "default/stackgres.v1.4.3" phase: Pending 
INFO[0035]   Found ClusterServiceVersion "default/stackgres.v1.4.3" phase: InstallReady 
INFO[0036]   Found ClusterServiceVersion "default/stackgres.v1.4.3" phase: Installing 
INFO[0076]   Found ClusterServiceVersion "default/stackgres.v1.4.3" phase: Succeeded 
INFO[0076] OLM has successfully installed "stackgres.v1.4.3" 
$ operator-sdk run bundle registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.5.0
INFO[0012] Creating a File-Based Catalog of the bundle "registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.5.0" 
INFO[0014] Generated a valid File-Based Catalog         
FATA[0014] Failed to run bundle: create catalog: error creating catalog source: catalogsources.operators.coreos.com "stackgres-catalog" already exists 
```

**Comment by teoincontatto** [comment]
Fond the error at last :sweat: 

```
    time="2023-07-05T08:12:37Z" level=fatal msg="Failed to run bundle upgrade: update catalog error: error creating registry: error building registry pod definition: configMap error: error updating ConfigMap: error creating ConfigMap: ConfigMap \"stackgres-catalog-configmap-partition-2\" is invalid: []: Too long: must have at most 1048576 bytes\n"
```

What can I do now?

**Comment by teoincontatto** [comment]
I was able to reproduce the issue locally by testing with `operator-sdk` 1.28.0. The upgrade failed with the same error as in the pipeline:

```
$ operator-sdk version
operator-sdk version: "v1.28.0", commit: "484013d1865c35df2bc5dfea0ab6ea6b434adefa", kubernetes version: "1.26.0", go version: "go1.19.6", GOOS: "linux", GOARCH: "amd64"
$ operator-sdk run bundle-upgrade registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.5.0 
INFO[0002] Found existing subscription with name stackgres-v1-4-3-sub and namespace default 
INFO[0002] Found existing catalog source with name stackgres-catalog and namespace default 
INFO[0014] Generated a valid Upgraded File-Based Catalog 
FATA[0014] Failed to run bundle upgrade: update catalog error: error creating registry: error building registry pod definition: configMap error: error updating ConfigMap: error creating ConfigMap: ConfigMap "stackgres-catalog-configmap-partition-2" is invalid: []: Too long: must have at most 1048576 bytes 
```

Testing with latest `operator-sdk` 1.30.0 solves the issue and the upgrade completed successfully.

```
$ operator-sdk version
operator-sdk version: "v1.30.0", commit: "b794fe909abc1affa1f28cfb75ceaf3bf79187e6", kubernetes version: "1.26.0", go version: "go1.19.10", GOOS: "linux", GOARCH: "amd64"
$ operator-sdk run bundle-upgrade registry.gitlab.com/ongresinc/stackgres/helm-operator-bundle:1.5.0
INFO[0002] Found existing subscription with name stackgres-v1-4-3-sub and namespace default 
INFO[0002] Found existing catalog source with name stackgres-catalog and namespace default 
INFO[0014] Generated a valid Upgraded File-Based Catalog 
INFO[0017] Created registry pod: istry-gitlab-com-ongresinc-stackgres-helm-operator-bundle-1-5-0 
INFO[0017] Updated catalog source stackgres-catalog with address and annotations 
INFO[0017] Deleted previous registry pod with name "istry-gitlab-com-ongresinc-stackgres-helm-operator-bundle-1-4-3" 
INFO[0029] Approved InstallPlan install-dtznh for the Subscription: stackgres-v1-4-3-sub 
INFO[0029] Waiting for ClusterServiceVersion "default/stackgres.v1.5.0" to reach 'Succeeded' phase 
INFO[0029]   Waiting for ClusterServiceVersion "default/stackgres.v1.5.0" to appear 
INFO[0032]   Found ClusterServiceVersion "default/stackgres.v1.5.0" phase: Pending 
INFO[0038]   Found ClusterServiceVersion "default/stackgres.v1.5.0" phase: InstallReady 
INFO[0039]   Found ClusterServiceVersion "default/stackgres.v1.5.0" phase: Installing 
INFO[0058]   Found ClusterServiceVersion "default/stackgres.v1.5.0" phase: Succeeded 
INFO[0058] Successfully upgraded to "stackgres.v1.5.0"  
```

Any chance to update `operator-sdk` used in CI tests?

**Comment by mporrato** [comment]
@teoincontatto I've bumped the operator-sdk version used by orange tests. Looks like newer operator-sdk versions have another bug that broke the installation of olm. I've used a workaround for now.

**Comment by teoincontatto** [comment]
Thanks @mporrato, very appreciate! :raised_hands:

**Pull request merged**
