### PR TITLE
operators [R] [CI] prometheus-exporter-operator (0.2.0 0.2.4 0.3.4)

### PR DESCRIPTION
**Pull request by slopezz**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by mvalarh** [comment]
@slopezz pipeline is not able to pull that image. Probably is it not public for reading. From my desktop i see the same
```
[mvala@fedora lvalova]$ podman pull quay.io/3scale/prometheus-exporter-operator
Trying to pull quay.io/3scale/prometheus-exporter-operator:latest...
Error: initializing source docker://quay.io/3scale/prometheus-exporter-operator:latest: reading manifest latest in quay.io/3scale/prometheus-exporter-operator: manifest unknown: manifest unknown
```

**Comment by J0zi** [comment]
@slopezz also an `image` string and `containerImage` string should be the same.

**Comment by slopezz** [comment]
Hi @J0zi ,

I don't mind adding the image tag on the metadata annotations `containerImage` field from the CSV, but first I would like to understand it:
- operator-sdk `make bundle` did not populate that field, although it adds the `VERSION` on many other places from the CSV, including the operator deployment (which should be the source of truth)
- These exact yamls were successfully to OpenShift operatorhub without any issue, passing successfully the **kiwi test** at https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/308

## K8s operatorhub wiki test

I have carefully reviewed the failing **kiwi test** output at https://github.com/k8s-operatorhub/community-operators/runs/4033776296?check_suite_focus=true

Before failing because it uses the metadata annotations `containerImage` (without the tag, so using non existing latest image), it tries to use the temporal image from the test at internal registry `kind-registry:5000/test-operator`, **but there is a typo**, it uses `kind-registry:5000/test-operator/catalog:latesti` instead of `kind-registry:5000/test-operator/catalog:latest` (**note the extra letter  `i` after latest**):

```
line 845 - ok
TASK [build_operators_index : Printing operators for index to be added] ********
ok: [localhost] => 
  operators_for_index:
  - bundles:
    - kind-registry:5000/test-operator/prometheus-exporter-operator:v0.3.4
    name: prometheus-exporter-operator
    versions:
    - 0.3.4
... 

line 915  - ok
TASK [operator_index : Add 'prometheus-exporter-operator' operator to index image kind-registry:5000/test-operator/catalog:latest] ***
changed: [localhost]
...

line 941 - ok
TASK [operator_index : Prints message that bundles were added to catalog] ******
ok: [localhost] => 
  msg: 'Bundles ''kind-registry:5000/test-operator/prometheus-exporter-operator:v0.3.4'''' were added and push to catalog ''kind-registry:5000/test-operator/catalog:latest'' using mode ''semver'' : [OK]'
...

line 991 - fatal
TASK [operator_ignore_list : Pull index image 'kind-registry:5000/test-operator/catalog:latesti'] ***
fatal: [localhost]: FAILED! => changed=true 
  cmd: podman pull kind-registry:5000/test-operator/catalog:latesti
  delta: '0:00:00.108305'
  end: '2021-10-28 11:17:17.771816'
  msg: non-zero return code
  rc: 125
  start: '2021-10-28 11:17:17.663511'
  stderr: |-
    Trying to pull kind-registry:5000/test-operator/catalog:latesti...
    Error: initializing source docker://kind-registry:5000/test-operator/catalog:latesti: reading manifest latesti in kind-registry:5000/test-operator/catalog: manifest unknown: manifest unknown
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
```

So as it fails, I guess as a fallback it tries to reach the real image from external registry using the metadata annotations `containerImage` field from the CSV, which does not contain the **tag** because operator-sdk `make bundle` did not populate it:

```
line 1072 - fatal
TASK [check_image_availability : Pull external operator image 'quay.io/3scale/prometheus-exporter-operator' on Kubernetes] ***
fatal: [localhost]: FAILED! => changed=true 
  cmd: podman pull quay.io/3scale/prometheus-exporter-operator
  delta: '0:00:00.852788'
  end: '2021-10-28 11:17:23.727695'
  msg: non-zero return code
  rc: 125
  start: '2021-10-28 11:17:22.874907'
  stderr: |-
    Trying to pull quay.io/3scale/prometheus-exporter-operator:latest...
    Error: initializing source docker://quay.io/3scale/prometheus-exporter-operator:latest: reading manifest latest in quay.io/3scale/prometheus-exporter-operator: manifest unknown: manifest unknown
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
```


## OpenShift operatorhub wiki test

I have checked the successful **kiwi test** from OpenShift operatorhub at https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/3975056535?check_suite_focus=true

And here it success because there is no typo and fetches correctly the internal registry image without using `latesti` tag:
```
line 877
TASK [validate_operator_bundle : Pull index image 'kind-registry:5000/test-operator/prometheus-exporter-operator:v0.3.4' (operator_sdk_none fix)] ***
changed: [localhost]

TASK [validate_operator_bundle : Validate the operator bundle manifest and metadata with operator-sdk bundle validate from image kind-registry:5000/test-operator/prometheus-exporter-operator:v0.3.4] ***
changed: [localhost]
```

So, is it possible the **kiwi test**  script has a typo (**latesti**) and this is the reason why this **kiwi test** fails on k8s but not on openshift operatorhub?

**Comment by mvalarh** [comment]
```

**Comment by mvalarh** [comment]
@slopezz please fill `containerImage` with tag and make sure that image is available for reading

**Comment by slopezz** [comment]
Hi @mvalarh , I have added a valid tag to the metadata annotation `containerImage`, now coincides with the operator deployment image, hopefully will pass the ci now

Shall I open a issue to operator-sdk in order to manage that field with the `make bundle` (like many other fields using the Makefile `VERSION`)?

It is a bit strange having to manage this field manually only for k8s operatorhub, but not for OpenShift operatorhub

**Comment by mvalarh** [comment]
> Hi @mvalarh , I have added a valid tag to the metadata annotation `containerImage`, now coincides with the operator deployment image, hopefully will pass the ci now
> 
> Shall I open a issue to operator-sdk in order to manage that field with the `make bundle` (like many other fields using the Makefile `VERSION`)?
I think it would be useful
> 
> It is a bit strange having to manage this field manually only for k8s operatorhub, but not for OpenShift operatorhub
I will have to check it, because there should be not any difference for this check

**Comment by J0zi** [comment]
@slopezz good idea ^

**Comment by J0zi** [comment]
@slopezz, installation failed
https://github.com/k8s-operatorhub/community-operators/runs/4104736619?check_suite_focus=true#step:6:1814

**Comment by slopezz** [comment]
Hi @J0zi, checking the ouput of the failing test it is seems it is failing on detecting the operator pod:
```
  cmd: kubectl get pods -n test-operators| grep prometheus-exporter-operator-controller-manager | grep Running
```


I have just installed on a dev OCP 4.8 cluster the same operator` v0.3.4` that was submitted succesfully a few weeks ago on [OpenShift community operators catalog](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/23929191a452c8015c2bcb6cad8d552de6488cb1/operators/prometheus-exporter-operator) without any issue (doing a fresh install):

image


**The yamls between OCP and K8s catalogs are 100% the same**, except the CSV metadata annotation with `containerImage` having the specific operator tag version that you told me I needed to add, because apparently the operator deployment image with correct tag was not enough in the k8s kiwi test 


Here you can see that yamls are identical on both catalogs (OCP **main** branch, and the one from this PR K8s **add-prometheus-exporter-operator.v0.3.4**) :

```bash
## Clone OCP catalog repo (main branch) with successful operator without issues

slopez @ ~/work/diff-operators $ git clone https://github.com/redhat-openshift-ecosystem/community-operators-prod.git
Cloning into 'community-operators-prod'...
remote: Enumerating objects: 40837, done.
remote: Counting objects: 100% (4619/4619), done.
remote: Compressing objects: 100% (1010/1010), done.
remote: Total 40837 (delta 3795), reused 4236 (delta 3543), pack-reused 36218
Receiving objects: 100% (40837/40837), 54.32 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (27278/27278), done.


# Clone k8s catalog operator (the one from this PR) and switch to PR branch

slopez @ ~/work/diff-operators  $ git clone git@github.com:slopezz/community-operators.git
loning into 'community-operators'...
remote: Enumerating objects: 40985, done.
remote: Counting objects: 100% (5278/5278), done.
remote: Compressing objects: 100% (2095/2095), done.
remote: Total 40985 (delta 3331), reused 4843 (delta 3076), pack-reused 35707
Receiving objects: 100% (40985/40985), 50.85 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (27033/27033), done.


slopez @ ~/work/diff-operators $ cd community-operators

slopez @ ~/work/diff-operators/community-operators (main)└─ $ git checkout add-prometheus-exporter-operator.v0.3.4
Branch 'add-prometheus-exporter-operator.v0.3.4' set up to track remote branch 'add-prometheus-exporter-operator.v0.3.4' from 'origin'.
Switched to a new branch 'add-prometheus-exporter-operator.v0.3.4'

slopez @ ~/work/diff-operators/community-operators (add-prometheus-exporter-operator.v0.3.4)└─ $ cd ..


# Recursive diff, only difference on the CSV annotation containerImage that you told me to change although it was working fine on OCP catalog

slopez @ ~/work/diff-operators $ diff -r community-operators/operators/prometheus-exporter-operator/ community-operators-prod/operators/prometheus-exporter-operator/
diff -r community-operators/operators/prometheus-exporter-operator/0.3.4/manifests/prometheus-exporter-operator.clusterserviceversion.yaml community-operators-prod/operators/prometheus-exporter-operator/0.3.4/manifests/prometheus-exporter-operator.clusterserviceversion.yaml
29c29
<     containerImage: quay.io/3scale/prometheus-exporter-operator:v0.3.4
---
>     containerImage: quay.io/3scale/prometheus-exporter-operator
```

So, what is the reason of the failure on the k8s catalog? 

Shouldn't OCP and K8s catalog be the same, where the difference is the target catalog repo image where the operators are pushed, but sharing same pipeline checks...?

**Comment by slopezz** [comment]
Hi, is there any update?

**Comment by mvalarh** [comment]
@slopezz Since there is conflict, is this PR still needed? If yes please rebase and reopen. Thanks

**Pull request closed without merging**
