### PR TITLE
operator [O] victoriametrics-operator (0.49.1)

### PR DESCRIPTION
**Pull request by tomasbakk**
This PR is meant to fix the broken bundle that is affecting releasing of k8s operators.

---

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Review by AndrewChubatiuk — APPROVED** [review]

**Review by mporrato — APPROVED** [review]

**Comment by AndrewChubatiuk** [comment]
for some reason version sort is broken in traffic light test
```
Versions Count: CHANGED[0.10.0 0.11.0 0.12.1 0.12.2 0.13.1 0.14.1 0.15.2 0.16.0 0.17.1 0.17.2 0.18.0 0.18.1 0.18.2 0.19.0 0.19.1 0.20.1 0.21.0 0.22.0 0.22.1 0.23.3 0.24.0 0.25.0 0.25.1 0.26.2 0.27.2 0.29.1 0.32.0 0.32.1 0.33.0 0.39.4 0.4.0 0.46.2 0.46.3 0.46.4 0.47.0 0.47.2 0.47.3 0.48.3 0.48.4 0.6.1 0.7.3 0.8.0 0.9.1] REMOVED[]
```
it tries to run 0.9.1, which uses deprecated API

**Comment by tomasbakk** [comment]
> for some reason version sort is broken in traffic light test
> 
> ```
> Versions Count: CHANGED[0.10.0 0.11.0 0.12.1 0.12.2 0.13.1 0.14.1 0.15.2 0.16.0 0.17.1 0.17.2 0.18.0 0.18.1 0.18.2 0.19.0 0.19.1 0.20.1 0.21.0 0.22.0 0.22.1 0.23.3 0.24.0 0.25.0 0.25.1 0.26.2 0.27.2 0.29.1 0.32.0 0.32.1 0.33.0 0.39.4 0.4.0 0.46.2 0.46.3 0.46.4 0.47.0 0.47.2 0.47.3 0.48.3 0.48.4 0.6.1 0.7.3 0.8.0 0.9.1] REMOVED[]
> ```
> 
> it tries to run 0.9.1, which uses deprecated API

yeah, I am trying to find out the reason why but to no avail yet. If I change the replaces strategy to see if it will align to the previous versions, it will fail on [semver](https://github.com/k8s-operatorhub/community-operators/actions/runs/11976183409/job/33391529491?pr=5341#step:3:10718) issues, even though the operator uses replace-mode update graph. In case I try to remove either latest or 2 latest versions, it will fail on that one. It looks like it is picking up the 0.8.0 going upwards.

**Comment by tomasbakk** [comment]
This might be just a shot into darkness, but comparing how the bundles are sorted during tests with bundles in the repo itself, It looks like test is picking up the versions one by one by how they are ordered in github repo instead of their actual bundle version.

**Comment by tomasbakk** [comment]
Thank you. Yes, I will close the PR.

**Comment by tomasbakk** [comment]
@AndrewChubatiuk Just a quick note; release of your operator for the latest bundle failed because there are some other operators out of sync, due to the recent problems. I run the manual release of said bundles and after the workflow is finished, your recent bundles should be release as well.

**Pull request closed without merging**
