### PR TITLE
operators [R] [CI] instana-agent-operator (1.0.0 1.0.2 1.0.4 1.0.5 1.0.6 1.0.7 1.0.8 1.0.9 2.0.0)

### PR DESCRIPTION
**Pull request by mdonkers**
Signed-off-by: Miel Donkers <miel.donkers@instana.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by mdonkers** [comment]
Dear maintainers,

The build is currently failing because the repository already contains the "package format" versions. We have overhauled our Operator and build from scratch using the Operator SDK. meaning we have now also switched to the bundle format.

Unfortunately guidelines are not fully clear on how to migrate an existing repository. I've tried the `olm` command but that is failing as I'm trying to migrate old versions one by one:

```shell
./opm alpha bundle build --directory 0.0.2/ --tag instana-agent-operator:0.0.2 --output-dir ./0.0.2
INFO[0000] Bundle channels and package name information not provided, inferring from parent package directory 
Error: please manually input channels and packageName, error interpreting bundle from directory /Development/projects/instana/community-operators/operators/instana-agent/0.0.2, error geting CSVs from bundles in the package directory, no ClusterServiceVersion object found in /Development/projects/instana/community-operators/operators/instana-agent/2.0.0
```

If you could provide any assistance on how to easily get the old versions migrated, that would be really helpful.

**Comment by mvalarh** [comment]
@mdonkers in short: Each operator version has to have same directory structure. Exactly like you have in https://github.com/instana/community-operators/tree/instana-agent-2.0.0/operators/instana-agent/2.0.0.

So you need to do following for each version directory
1. move csv and all crds files to `manifests` directory
2. create metadata directory and put `annotations.yaml`
3. Port information from `instana-agent.package.yaml` to `metadata/annotations.yaml`
4. Optional, copy `tests/scorecard` to each directory and specify its location in `annotations.yaml` if needed
5. Remove `instana-agent.package.yaml`

And this should be it. Your final directory structure could look like [this](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/cockroachdb)

**Comment by mdonkers** [comment]
@mvalarh Thanks a lot for your guidance.
With some manual work (and scripting) I've managed to update previous versions and those appear to be (mostly) correct now. Some important notes though:
- We decided to leave out versions before `1.0.0` as we never published them with the correct meta-data / annotations. So I would have needed to reconstruct those from scratch. I believe we have no customers on such old versions though (they were 'alpha' anyhow).
- We found out some discrepancies in naming; old versions were using `instana-agent` and `instana-agent-operator` next to each other. `instana-agent` was used for the directory name and in the `annotations.yaml` but `instana-agent-operator` everywhere else. Since the Operator SDK guides us, everything should now be named `instana-agent-operator` correctly. Therefore we also changed the base directory for the community operator, and updated older versions with the `annotations.yaml` to point to `instana-agent-operator` as well. I hope this is correct and doesn't lead to backwards compatibility issues? As I wouldn't know how to handle it differently...

With this, most of the tests are passing. Only "lemon - deploy from scratch" is failing: https://github.com/k8s-operatorhub/community-operators/runs/4236916236?check_suite_focus=true
Could you shed some light on what might be wrong?
Could this be because of the `replaces` / `skipVersion`? As for the RHEL marketplace because old versions were removed, we cannot use `replaces` and thus set;
```
metadata:
  annotations:
    olm.skipRange: <2.0.0
```
I expect this would be compatible with the non RHEL OLM bundle as well?

**Comment by mvalarh** [comment]
@mdonkers in our pipeline you can remove anything. We are rebuilding operator in such case. So feel free to remove operator versions you don't support anymore.

**Comment by mdonkers** [comment]
Side note: seems like the pipeline is not fully reliable as downloading a bash script fails (unrelated to updates here):
```
TASK [install_operator_prereqs : Download dyff] ********************************
fatal: [localhost]: FAILED! => changed=true 
  cmd: curl --silent --location https://tinyurl.com/y4qvdl4d | bash
  delta: '0:00:00.071275'
  end: '2021-11-18 09:13:13.236157'
  failed_when_result: true
  msg: non-zero return code
  rc: 2
  start: '2021-11-18 09:13:13.164882'
  stderr: |-
    bash: line 1: syntax error near unexpected token `newline'
    bash: line 1: `<!DOCTYPE HTML>'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Pull request merged**
