### PR TITLE
operator wildfly (1.0.0)

### PR DESCRIPTION
**Pull request by yersan**
Upgrade WildFly Operator to 1.0.0

Signed-off-by: Yeray Borges <yborgess@redhat.com>

### CODE REVIEW

**Comment by yersan** [comment]
Hello @Allda / @mporrato `Operator test / orange / Deploy k8s (latest) (pull_request_target)` failed with the following message:

```
TASK [test_operator_update : Logs] *********************************************
fatal: [localhost]: FAILED! => changed=true 
  cmd: kubectl logs kind-registry-5000-test-operator-wildfly-v1-0-0 -n default
  delta: '0:00:00.055139'
  end: '2024-02-27 14:11:32.346100'
  msg: non-zero return code
  rc: 1
  start: '2024-02-27 14:11:32.290961'
  stderr: 'Error from server (NotFound): pods "kind-registry-5000-test-operator-wildfly-v1-0-0" not found'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring

TASK [test_operator_update : Show logs] ****************************************
ok: [localhost] => 
  tou_pod_log:
    changed: true
    cmd: kubectl logs kind-registry-5000-test-operator-wildfly-v1-0-0 -n default
    delta: '0:00:00.055139'
    end: '2024-02-27 14:11:32.346100'
    failed: true
    msg: non-zero return code
    rc: 1
    start: '2024-02-27 14:11:32.290961'
    stderr: 'Error from server (NotFound): pods "kind-registry-5000-test-operator-wildfly-v1-0-0" not found'
    stderr_lines:
    - 'Error from server (NotFound): pods "kind-registry-5000-test-operator-wildfly-v1-0-0" not found'
    stdout: ''
    stdout_lines: []

TASK [test_operator_update : Update status if wrong] ***************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Operator upgrade failed, you can debug locally by 2 commands: ''operator sdk run bundle BUNDLE_N-1; operator-sdk run bundle-upgrade BUNDLE_N''  [FAIL]'

PLAY RECAP *********************************************************************
localhost                  : ok=890  changed=202  unreachable=0    failed=1    skipped=839  rescued=0    ignored=2   

Error: Process completed with exit code 2.
```

Do you have any clue about the reasons?

**Comment by haripate** [comment]
@yersan I will look into the issue.

**Comment by yersan** [comment]
From a very naive perspective, the failed command seems to be looking for a pod on the default namespace:

`cmd: kubectl logs kind-registry-5000-test-operator-wildfly-v1-0-0 -n default`

However, this pod is running on `testupgrade` namespace instead:

```
TASK [test_operator_update : Show logs] ****************************************
ok: [localhost] => 
  tou_pods:
    changed: true
    cmd: kubectl get pods --all-namespaces
    delta: '0:00:00.082463'
    end: '2024-02-28 23:47:56.816463'
    failed: false
    msg: ''
    rc: 0
    start: '2024-02-28 23:47:56.734000'
    stderr: ''
    stderr_lines: []
    stdout: |-
      NAMESPACE            NAME                                                              READY   STATUS      RESTARTS      AGE
      ....
      testupgrade          kind-registry-5000-test-operator-wildfly-v1-0-0                   1/1     Running     0             109s
      ....
```

**Comment by haripate** [comment]
@yersan I tried to install and run the v1.0.0 locally and here is what I found. https://gist.github.com/haripate/2dd2ee025d4e1f49f0748459609db586

In my initial attempt, I installed the previous version v0.5.6 and then attempted to upgrade it to v1.0.0. This approach failed, as shown in the above gist. However, I then attempted to install v1.0.0 directly, and it was successful. I am assuming that the issue lies with some kind of lock prevention during the upgrade process. I hope this information helps you to determine the root cause of the problem.

**Comment by yersan** [comment]
@haripate thanks for the hints, yes, there was a problem with the leader election and the upgrade. Jobs looks green now, thanks!

**Comment by yersan** [comment]
Hello, @haripate / @tomasbakk , would you mind providing some information about when this release can be published?

PR has been ready since two weeks ago. Is there anything I can do to move it up?, thanks!

**Pull request merged**
