### PR TITLE
operators [R] [CI] jaeger (1.11.0 1.11.1 1.12.0 1.12.1 1.13.0 1.13.1 1.14.0 1.15.0 1.16.0 1.17.0 1.17.1 1.18.0 1.18.1 1.19.0 1.20.0 1.21.3 1.22.1 1.24.0 1.25.0 1.26.0 1.28.0 1.29.1)

### PR DESCRIPTION
**Pull request by rkukura**
Add v1.29.1 and convert previous versions to new bundle format.

Signed-off-by: Robert Kukura <rkukura@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by J0zi** [comment]
@rkukura   Value of `metadata.annotations.containerImage` not used in any container, please check.
    The operator is using some image which must have exactly the same value as `metadata.annotations.containerImage`.
    Please check both values and make them the same.

**Comment by rkukura** [comment]
> @rkukura Value of `metadata.annotations.containerImage` not used in any container, please check. The operator is using some image which must have exactly the same value as `metadata.annotations.containerImage`. Please check both values and make them the same.

This isn't making sense to me. Unless I'm mistaken, this `metadata.annotations.containerImage` is from the bundle's CSV and identifies the image for OLM to deploy in a container as the operator. This image does seem to exist. What would cause some different image, or no image at all, to be deployed instead? Or does "used in any container" mean something different than being deployed in a container by OLM?

BTW, 1.8.2 is a very old version, and both the CSV and CRD have changed significantly in subsequent versions. I'm tempted to simply remove 1.8.2 and see if the newer versions pass CI.

**Comment by J0zi** [comment]
Unable to pull quay.io/jaegertracing/jaeger-operator, please check permissions or path.

**Comment by J0zi** [comment]
@rkukura, it has [failed](https://github.com/k8s-operatorhub/community-operators/runs/4553947466?check_suite_focus=true#step:6:2806) on `api-server resource not found installing ServiceMonitor jaeger-operator-metrics-monitor: GroupVersionKind monitoring.coreos.com/v1, Kind=ServiceMonitor not found on the cluster`

**Pull request merged**
